/*
	This is the code follows the style of a  a pico-go cartridge.

	However as the functionality differs it IS ok to change the code as is will not be autogenerated.

*/

//go:generate file2byteslice -package=main -input=./sprites.gif -output=./gen-sprites.go -var=sprites_gif
//go:generate gopherjs build --minify -o ../../resources/app/static/js/gen-spriteEd.js

package main

import (
	"fmt"

	"github.com/gopherjs/gopherjs/js"
	"github.com/telecoda/pico-go-electron/console"
)

func NewCart() console.Cartridge {
	return &cartridge{
		BaseCartridge: console.NewBaseCart(),
	}
}

func main() {
	cart := NewCart()
	if err := console.Init(consoleType); err != nil {
		fmt.Printf("Failed to init console: %s\n", err)
		return
	}

	spriteData = "ABCDEFG"
	fmt.Printf("JS functions initialised\n")
	// register functions
	js.Global.Get("localStorage").Set("sprite-data", sprites_gif)

	if err := console.Run(cart); err != nil {
		fmt.Printf("Failed to run cartridge: %s\n", err)
		return
	}
}

var spriteData string

func GetSpritesData() string {
	return spriteData
}

func SetSpritesData(data string) {
	spriteData = data
}

func Hello() string {
	fmt.Printf("Hello\n")
	return "foo"
}
